data <- read.table("./exdata_data_household_power_consumption/household_power_consumption.txt", sep = ";", header = TRUE, dec = ".", stringsAsFactors = FALSE)
dataSubset <- data[data$Date %in% c("1/2/2007","2/2/2007") ,]
datetime <- strptime(paste(dataSubset$Date, dataSubset$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
GlobalActivePower <- as.numeric(dataSubset$Global_active_power)
Voltage <- as.numeric(dataSubset$Voltage)
Sub_metering_1 <- as.numeric(dataSubset$Sub_metering_1)
Sub_metering_2 <- as.numeric(dataSubset$Sub_metering_2)
Sub_metering_3 <- as.numeric(dataSubset$Sub_metering_3)
Global_reactive_power <- as.numeric(dataSubset$Global_reactive_power)
png(filename = "plot4.png", width = 480, height = 480)
par(mfcol = c(2, 2))
plot(datetime, GlobalActivePower, type = "l", xlab = "", ylab = "Global Active Power")
plot(datetime, Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(datetime, Sub_metering_2, type = "l", xlab = "", col = "red")
lines(datetime, Sub_metering_3, type = "l", xlab = "", col = "blue")
legend("topright", lty = c(1, 1, 1), bty = "n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(datetime, Voltage, type = "l", ylab = "Voltage")
plot(datetime, Global_reactive_power, type = "l", ylab = "Global_reactive_power")
dev.off()